### ISSUE TITLE
training_data_nonCG.txt does not exist

### ISSUE THREAD

**Issue by Papareddy** [ListerLab/HOME#14]
Hello There,

Fairly new informatics.. sorry if it as naive question eating up a bit of your time.
I tried running home on both pairwise and time series mode for my sample at CHH and CHG context its giving me no DMrs while giving a note stating non_CG data not trained.

Am I missing something obvious. Please find the error below

cheers and many thanks,
Ranj.
ranjith.papareddy@dmn3 [~/HOME/tspool]> HOME-pairwise -t CHG -i ~/HOME/tspool/timeseries.tsv -o ~/HOME/tspool/ -npp 32 
Preparing the DMRs from HOME.....
GOOD LUCK !
/net/gmi.oeaw.ac.at/software/mendel/29_04_2013/software/statsmodels/0.8.0-foss-2017a-Python-2.7.13/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/stats/weightstats.py:670: RuntimeWarning: invalid value encountered in double_scalars
  zstat = value / std_diff
/net/gmi.oeaw.ac.at/software/mendel/29_04_2013/software/statsmodels/0.8.0-foss-2017a-Python-2.7.13/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/stats/weightstats.py:670: RuntimeWarning: invalid value encountered in double_scalars
  zstat = value / std_diff
/net/gmi.oeaw.ac.at/software/mendel/29_04_2013/software/statsmodels/0.8.0-foss-2017a-Python-2.7.13/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/stats/weightstats.py:670: RuntimeWarning: invalid value encountered in double_scalars
  zstat = value / std_diff
/net/gmi.oeaw.ac.at/software/mendel/29_04_2013/software/statsmodels/0.8.0-foss-2017a-Python-2.7.13/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/stats/weightstats.py:670: RuntimeWarning: invalid value encountered in double_scalars
  zstat = value / std_diff
/net/gmi.oeaw.ac.at/software/mendel/29_04_2013/software/statsmodels/0.8.0-foss-2017a-Python-2.7.13/lib/python2.7/site-packages/statsmodels-0.8.0-py2.7-linux-x86_64.egg/statsmodels/stats/weightstats.py:670: RuntimeWarning: invalid value encountered in double_scalars
  zstat = value / std_diff
File /home/GMI/ranjith.papareddy/HOME/tspool/training_data/training_data_nonCG.txt does not exist

**Comment by Akanksha2511** [comment]
Hi, 
Please run it from within the HOME directory, not tspool. Also please make sure the versions of python packages match as required by the tool. 

Thanks,
Akanksha

**Comment by Papareddy** [comment]
Hi thanks for the response,

I did so but if no avail. I thought knits an issue with our HPC most probably ...

Cheers and thanks again 
Ranj
