### ISSUE TITLE
HOME-timeseries error

### ISSUE THREAD

**Issue by decaturjim** [ListerLab/HOME#16]
Hi,

I'm having an issue with HOME-timeseries. I'm running a comparison over four time-points with two replicates per time-point. The data is formatted like this:

```
chr1    10708   +       CG      3       3
chr1    10718   +       CG      3       3
chr1    10720   +       CG      3       3
chr1    10723   +       CG      3       3
chr1    10725   +       CG      3       3
chr1    10728   +       CG      3       3
chr1    10731   +       CG      3       3
chr1    10737   +       CG      2       2
chr1    12807   +       CG      1       1
chr1    13079   +       CG      4       7
```

This is the command I'm using:

```
HOME-timeseries -t CG -i /jim/HOME_analysis/meta_ct_time.txt -o /jim/HOME_analysis/output_ct_time/ --delta 0.25 --minc 5
```

This is the error I am getting:

```
Preparing the DMRs from HOME.....
GOOD LUCK !
Traceback (most recent call last):
  File "/jim/homenvir/bin/HOME-timeseries", line 4, in <module>
    __import__('pkg_resources').run_script('HOME==0.5', 'HOME-timeseries')
  File "/jim/homenvir/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/jim/homenvir/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace) 
  File "/jim/homenvir/local/lib/python2.7/site-packages/HOME-0.5-py2.7.egg/EGG-INFO/scripts/HOME-timeseries", line 489, in <module>

  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
Exception: 'numpy.ndarray' object has no attribute 'columns'
```
All prerequisites are the correct versions and I'm using a virtual environment. HOME-pairwise using the same data works great.

Thanks for your help,

Jim

**Comment by Akanksha2511** [comment]
Hi Jim, really sorry about the issue, was a bug in an updated script for HOME-0.5. I have corrected it and updated the GitHub repository, it should be fine now. Please remember to delete the temp_HOME folder and HOME_timeseries_DMRs directory (that might be created from your previous run) from your output path, before starting a new run. Thanks for reporting the issue, and please feel free to contact if there are any further issues or queries. 

Thanks,
Akanksha

**Comment by decaturjim** [comment]
Hi Akanksha, no worries. The fix worked - everything is running smoothly again. Thanks for looking into that.

Cheers,

Jim
