### ISSUE TITLE
sample path

### ISSUE THREAD

**Issue by QGouil** [ListerLab/HOME#17]
Hi,
I found that the sample paths in the sample.tsv input have to be relative to the folders that HOME-pairwise creates, rather than relative to where the sample.tsv file is.
For instance if I call 

```bash
HOME-pairwise -t CG -i ./wt_vs_mut.txt -o ./wt_vs_mut/
```

then the command creates the output directory wt_vs_mut/HOME_pairwise_DMRs/wt_VS_mut/
and the input file wt_vs_mut.txt has to be something like:
wt ../../../methylation_data_wt1.txt
mut ../../../methylation_data_mut1.txt

It would be more intuitive if the sample path had to be relative to either the sample.tsv file, or relative to where the command is called.

**Comment by Akanksha2511** [comment]
Hi, 
For the current versions, it requires the complete path for the input file and output directory. Working on the relative path and will be updated in the future version.
Thanks,
Akanksha
