### ISSUE TITLE
cannot open file './scripts/HOME_R.R': No such file or directory

### ISSUE THREAD

**Issue by QGouil** [ListerLab/HOME#18]
It seems that if HOME-pairwise isn't run from the HOME installation directory, it cannot find HOME_R.R and in the end stops with 
Exception: 'DataFrame' object has no attribute 'p_value'

**Comment by QGouil** [comment]
Interestingly that's a problem on my laptop but not on the cluster. I made both installations with conda.

**Comment by Akanksha2511** [comment]
yes, it needs to be run from HOME installation directory.
