### ISSUE TITLE
HOME-pairwise script is missing

### ISSUE THREAD

**Issue by ebirn** [ListerLab/HOME#19]
Hi,

setup.py in v0.8 references a HOME-pairwise files, that does not exist. see https://github.com/ListerLab/HOME/blob/0.8/setup.py

Also the versions are inconsistent:
Releases page shows 'Release 0.5' which is tagged as 0.8 in git, however setup.py in that tag shows 0.4.
This makes it very hard to provide installations on shared computer systems.

Best,
Erich

**Comment by Akanksha2511** [comment]
Hi Erich, 

 Sorry about the issue and thanks for reporting it.  I have updated the release 0.5. 

Thanks, 
Akanksha
