### ISSUE TITLE
Error when finding DMR's with scaffolded genome

### ISSUE THREAD

**Issue by williamtjordan** [ListerLab/HOME#22]
Hello,

I am encountering the following error when attempting to find DMR's with a scaffolded genome:

File ".local/bin/HOME-pairwise", line 4, in <module>
  __import__('pkg_resources').run_script('HOME==0.6', 'HOME-pairwise')
File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 748, in run_script
File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1524, in run_script
File "/.local/lib/python2.7/site-packages/HOME-0.6-py2.7.egg/EGG-INFO/scripts/HOME-pairwise", line 466, in <module>

File "/usr/local/apps/eb/Python/2.7.14-foss-2016b/lib/python2.7/multiprocessing/pool.py", line 572, in get
  raise self._value
Exception: cannot convert the series to <type 'int'>

Any help resolving the issue would be most appreciated!

**Comment by Akanksha2511** [comment]
Hi,

Can you please share few lines of your input file and the run command. 

Thanks,
Akanksha

**Comment by williamtjordan** [comment]
1000011	496	-	CG	1	2
1000011	533	-	CG	2	2
1000091	180	+	CG	0	7
1000091	181	-	CG	0	23
1000091	353	+	CG	1	11
1000091	354	-	CG	1	23
1000091	531	+	CG	0	7
1000091	532	-	CG	0	8
1000091	544	+	CG	0	6
1000091	545	-	CG	0	7

Attached above is a sample of my tab-delimited input files, and the run command is as follows: 

HOME-pairwise -t CG   -i	home_DMR/samples.tsv -o	results/home_DMR -npp 8


Thanks for your help!

**Comment by Akanksha2511** [comment]
Thanks, the file format and the run command looks ok. Can you please share the files with me. If the files are small pls share the entire file otherwise maybe just first 1000 lines from each file. My email Id is  21447915@student.uwa.edu.au

**Comment by Akanksha2511** [comment]
Exception handling added in the new version
