### ISSUE TITLE
double scalar error

### ISSUE THREAD

**Issue by bhofmei** [ListerLab/HOME#27]
I keep getting this error running timeseries with CHH context. Just wondering if you know what is causing it or how to fix it.
```
RuntimeWarning: invalid value encountered in double_scalars
  zstat = value / std_diff
```
Also, can you update the documentation/README to say what `NA` means in the timeseries combn-1 columns? Current documentation says these cells have `start:end:state:delta` but most of mine are `NA` even with high confidence scores. Just trying to understand.

**Comment by Akanksha2511** [comment]
Hi, 
You can ignore the runtime warning. It occurs when division by zero is encountered. 
NA means that HOME did not find any significant DMR for that sample comparison. Will update that on the documentation. Also, if you are getting too many NAs it might be worth trying running HOME pairwise for multiple samples. So, if you run the same sample file path used for timeseries in normal HOME pairwise mode you will get DMRs for each comparison and then you can merge them to get the final DMRs for all sample comparison. Please let me know if you have any other issues/doubts. 
Thanks,
Akanksha

**Comment by bhofmei** [comment]
Thank you for the explanation. I was guessing that NA meant it wasn’t signficant but then I didn’t understand why the DMR would be included in the output when it was NA at all comparisons.

I had tried the pairwise technique before but was struggling to elegantly merge the DMRs afterwards and comparisons afterwards. It appears that bedtools merge would work to find a master list of DMRs and maybe say what comparison it came from, but it’s still not elegant since the new DMR boundaries, and potentially multiple testing correction, could change the statistical significance. My data is definitely time series, so if I were to use this technique, would you suggest merging from all comparisons or only the timeseries-relevant ones?

**Comment by Akanksha2511** [comment]
Hard to say, without looking into the data. I would suggest merging for all comparisons, otherwise, how would you find the time series-relevant ones?.

**Comment by bhofmei** [comment]
Okay thank you! I'll try that. FWIW, it would be awesome if you added some sort of try-catch or error check for the the divisible by zero error. Otherwise it's difficult to tell if the program actually finished and finished correctly.

**Comment by Akanksha2511** [comment]
yes sure. Thanks
