### ISSUE TITLE
Issue 20# Home run doesn’t end 

### ISSUE THREAD

**Issue by Papareddy** [ListerLab/HOME#30]
Hi Akanksha,

Just to be sure, is HOME compatable for single replicate timeseries analysis (or pairwise) ?. I have HOME (>0.7) working well for both timeseries or pairewise when i have multi replicates but never ending job run for single replicates as Nuria mentioned(with or without -sin paramether ). Do you think is there something do with single replicate experiments. And i also see double scalar error in these cases. We use the same HPC.

Cheers,
Ranj

**Comment by Akanksha2511** [comment]
Hi Ranj, yes it does work for single replicate data. In fact, it should be much quicker with single replicate data. It's tested on HPC and works fine. If you can share the files, I will be happy to look into what's causing the issue. 

Cheers,
Akanksha

**Comment by Papareddy** [comment]
input files were tab seperated BTW

**Comment by Akanksha2511** [comment]
Hi, the input file format seems ok. Which context are you running it for? ..how big are the files? Can you try it on some other system and see how much time it takes to complete? Also, may be good to try on small input files first.

**Comment by Papareddy** [comment]
I am running for  CG and arabidopsis genome (fairly small)..Yeah it was running nicely for timeseries with same conditions for multi rep exeriments.Only change atm was all comparisions are single replicates. Will have to trying some thing.

Cheers,
Ranj

**Comment by Akanksha2511** [comment]
Yes, try it on the small test case and see if it finishes. Sorry, for the issue but will have to try a few things to resolve it.
