### ISSUE TITLE
HOME ubale to open X server

### ISSUE THREAD

**Issue by pgonarz** [ListerLab/HOME#32]
I have installed HOME after creating an environment for python2.7 as described in the github installation instructions. Upon downloading the testdata (or trying to use my own), I get this error log while running HOME from the testdata directory:

HOME-pairwise -t CG -i ./sample_file_CG.txt -o ./CG -npp 24
/home/pgontarz/HOME_env/local/bin/HOME-pairwise: line 6: $'\nCreated on Mon Apr 16 12:15:36 2018\n\n@author: akanksha\n': command not found
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
from: can't read /var/mail/collections
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
from: can't read /var/mail/collections
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
from: can't read /var/mail/HOME
from: can't read /var/mail/os.path
/home/pgontarz/HOME_env/local/bin/HOME-pairwise: line 25: syntax error near unexpected token `('
/home/pgontarz/HOME_env/local/bin/HOME-pairwise: line 25: `def remEmptyDir(mypath):'

I am wondering if there is some issue with my installation of HOME? Building the virutalenv ran with no errors reported as did source <HOME_env>/bin/activate. 

pgontarz@regmedhpc2:~$ virtualenv -p /usr/bin/python2.7 HOME_env
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/pgontarz/HOME_env/bin/python2.7
Also creating executable in /home/pgontarz/HOME_env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
pgontarz@regmedhpc2:~$ source HOME_env/bin/activate
(HOME_env) pgontarz@regmedhpc2:~$ which python
/home/pgontarz/HOME_env/bin/python
(HOME_env) pgontarz@regmedhpc2:~$ which pip
/home/pgontarz/HOME_env/bin/pip
(HOME_env) pgontarz@regmedhpc2:~$ pip -V
pip 20.2.3 from /home/pgontarz/HOME_env/local/lib/python2.7/site-packages/pip (python 2.7)
(HOME_env) pgontarz@regmedhpc2:~$ pip install git+https://github.com/ListerLab/HOME.git
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting git+https://github.com/ListerLab/HOME.git
  Cloning https://github.com/ListerLab/HOME.git to /tmp/pip-req-build-ljgoAz
Collecting numpy
  Using cached numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl (17.0 MB)
Processing ./.cache/pip/wheels/e8/2f/e8/dcb43af3774d04ee19d01758335fc91a72c5074f8437a76dad/pandas-0.17.1-cp27-cp27mu-linux_x86_64.whl
Collecting scipy==0.16.0
  Using cached scipy-0.16.0-cp27-cp27mu-manylinux1_x86_64.whl (38.2 MB)
Collecting scikit-learn==0.16.1
  Using cached scikit-learn-0.16.1.tar.gz (7.3 MB)
Processing ./.cache/pip/wheels/70/29/19/37b211c5de170f745ec0875af6b3e7cf293a4e70b0491aa455/statsmodels-0.6.1-cp27-cp27mu-linux_x86_64.whl
Collecting pytz>=2011k
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting patsy
  Using cached patsy-0.5.1-py2.py3-none-any.whl (231 kB)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: HOME, scikit-learn
  Building wheel for HOME (setup.py) ... done
  Created wheel for HOME: filename=HOME-1.0.0-py2-none-any.whl size=20971 sha256=3766aa49664dfcd6f6ee969c5500e84be7e2d9906188f1828a10a0bf54d7cd06
  Stored in directory: /tmp/pip-ephem-wheel-cache-xvBrvW/wheels/33/77/39/0699ff79d381c958b6df0835f85b05d941395fe1bf6da305cd
  Building wheel for scikit-learn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pgontarz/HOME_env/bin/python2.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q3xJqc/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q3xJqc/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-lpsMHo
       cwd: /tmp/pip-install-q3xJqc/scikit-learn/
  Complete output (8 lines):
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-q3xJqc/scikit-learn/setup.py", line 173, in <module>
      setup_package()
    File "/tmp/pip-install-q3xJqc/scikit-learn/setup.py", line 165, in setup_package
      from numpy.distutils.core import setup
  ImportError: No module named numpy.distutils.core
  ----------------------------------------
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Successfully built HOME
Failed to build scikit-learn
Installing collected packages: numpy, pytz, six, python-dateutil, pandas, scipy, scikit-learn, patsy, statsmodels, HOME
    Running setup.py install for scikit-learn ... done
  DEPRECATION: scikit-learn was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Successfully installed HOME-1.0.0 numpy-1.16.6 pandas-0.17.1 patsy-0.5.1 python-dateutil-2.8.1 pytz-2020.1 scikit-learn-0.16.1 scipy-0.16.0 six-1.15.0 statsmodels-0.6.1

**Comment by Akanksha2511** [comment]
Hi, Could you please provide the complete path for  ./sample_file_CG.txt and give it a go. 

Thanks, 
Akanksha
